use super::*;
use flock_core::circuit::boolean::{
    ColumnRole, EvaluationError, InteractionDirection, InteractionEncoding, RowKind,
};
use flock_core::r1cs::BlockR1cs;

mod fixtures;
mod lowering;
use fixtures::{candidate, input_cases};

// Generated by memory/instructions/load/load_byte.rs at SP1 commit
// 4f56564727906846f80b30532dde26eacfc7e44c via LoadByteChip::generate_trace.
const SP1_TRACE_ROWS: [Sp1TraceRow; 3] = [
    Sp1TraceRow {
        is_lb: true,
        address_limbs: [2, 1, 0],
        offset: [false, true, false],
        memory_limbs: [8721, 17459, 26197, 34935],
        selected_limb: 17459,
        selected_low: 51,
        selected_byte: 51,
        msb: false,
    },
    Sp1TraceRow {
        is_lb: true,
        address_limbs: [7, 2, 0],
        offset: [true, true, true],
        memory_limbs: [8208, 16432, 24656, 32880],
        selected_limb: 32880,
        selected_low: 112,
        selected_byte: 128,
        msb: true,
    },
    Sp1TraceRow {
        is_lb: false,
        address_limbs: [5, 3, 0],
        offset: [true, false, true],
        memory_limbs: [12816, 30292, 47768, 65244],
        selected_limb: 47768,
        selected_low: 152,
        selected_byte: 186,
        msb: false,
    },
];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Sp1TraceRow {
    is_lb: bool,
    address_limbs: [u16; 3],
    offset: [bool; 3],
    memory_limbs: [u16; 4],
    selected_limb: u16,
    selected_low: u8,
    selected_byte: u8,
    msb: bool,
}

fn event(opcode: LoadByteOpcode, b: u64, c: u64, memory_value: u64) -> LoadByteEvent {
    LoadByteEvent {
        opcode,
        b,
        c,
        memory_value,
    }
}

fn word(bits: &[bool]) -> u64 {
    bits.iter()
        .enumerate()
        .fold(0, |word, (bit, &set)| word | (u64::from(set) << bit))
}

fn decode(values: &[bool], bits: &[ValueId]) -> u64 {
    bits.iter().enumerate().fold(0, |word, (bit, value)| {
        word | (u64::from(values[value.index()]) << bit)
    })
}

fn physical(lowered: &LoweredCircuit, logical: &[bool], k_log: usize) -> Vec<bool> {
    assert_eq!(logical.len(), lowered.value_count());
    let mut values = vec![false; 1 << k_log];
    for (&position, &value) in lowered.layout().value_positions().iter().zip(logical) {
        values[position] = value;
    }
    values
}

fn matrix(lowered: &LoweredCircuit) -> BlockR1cs {
    let k_log = lowered
        .layout()
        .useful_bits()
        .next_power_of_two()
        .trailing_zeros() as usize;
    lowered.to_block_r1cs(k_log, 0, 0).unwrap()
}

#[test]
fn sp1_reference_trace_and_interactions_survive_lowering() {
    let events = [
        event(LoadByteOpcode::Lb, 0x1_0000, 2, 0x8877_6655_4433_2211),
        event(LoadByteOpcode::Lb, 0x2_0000, 7, 0x8070_6050_4030_2010),
        event(LoadByteOpcode::Lbu, 0x3_0004, 1, 0xfedc_ba98_7654_3210),
    ];
    let expected = [0x33, 0xffff_ffff_ffff_ff80, 0xba, 0];
    let chip = LoadByteCircuit::build(4);
    let trace = chip.generate_trace(&events).unwrap();
    let inputs = chip.honest_inputs(&events);
    assert_eq!(trace.values, chip.circuit().evaluate(&inputs).unwrap());
    assert_eq!(events.map(LoadByteEvent::result), expected[..3]);
    for (row, cols) in trace.rows.iter().enumerate() {
        assert_eq!(cols.real, row < events.len());
        assert_eq!(word(&cols.result), expected[row]);
        assert_eq!(chip.output(&trace.values, row), expected[row]);
        if row < events.len() {
            let address = word(&cols.address.value);
            let memory = word(&cols.memory_value);
            let selected_limb = (memory >> (16 * ((address >> 1) & 3))) as u16;
            assert_eq!(
                Sp1TraceRow {
                    is_lb: cols.is_lb,
                    address_limbs: std::array::from_fn(|i| (address >> (16 * i)) as u16),
                    offset: cols.address.value[..3].try_into().unwrap(),
                    memory_limbs: std::array::from_fn(|i| (memory >> (16 * i)) as u16),
                    selected_limb,
                    selected_low: selected_limb as u8,
                    selected_byte: word(&cols.selected_byte) as u8,
                    msb: cols.sign,
                },
                SP1_TRACE_ROWS[row]
            );
            assert_eq!(cols.is_lbu, !cols.is_lb);
        }
    }
    assert_eq!(
        chip.compiled()
            .schema()
            .iter()
            .filter(|field| field.role == ColumnRole::Advice(ADVICE_TYPE))
            .count(),
        4
    );
    assert_eq!(chip.compiled().operations().len(), 12);

    for mode in [LoweringMode::Direct, LoweringMode::RequireIdentityC] {
        let lowered = chip.lower(mode).unwrap();
        let values = lowered.evaluate(&inputs).unwrap();
        assert_eq!(lowered.project(&values).unwrap(), trace.values);
        let matrix = matrix(&lowered);
        let walked = lowered
            .walk_plan()
            .unwrap()
            .forward(&inputs, matrix.k_log)
            .unwrap();
        assert_eq!(walked.z, physical(&lowered, &values, matrix.k_log));
        assert!(matrix.satisfies(&walked.z));
        assert_eq!(walked.a_z, matrix.apply_a(&walked.z));
        assert_eq!(walked.b_z, matrix.apply_b(&walked.z));
        assert_eq!(walked.c_z, matrix.apply_c(&walked.z));
        assert_eq!(lowered.interactions().len(), 8);
        for (row, cols) in chip.columns().iter().enumerate() {
            let mapped = |value| lowered.mapped_value(value).unwrap();
            let memory = &lowered.interactions()[2 * row];
            let register = &lowered.interactions()[2 * row + 1];
            for (interaction, channel, kind) in
                [(memory, "memory", "read"), (register, "register", "write")]
            {
                assert_eq!(interaction.channel(), channel);
                assert_eq!(interaction.kind(), kind);
                assert_eq!(interaction.direction(), InteractionDirection::Send);
                assert_eq!(interaction.scope().row(), row);
                assert_eq!(interaction.selector(), mapped(cols.real));
                assert_eq!(decode(&values, interaction.multiplicity()), 1);
                assert_eq!(
                    interaction.effective_multiplicity_bits(&values),
                    [row < events.len()]
                );
                assert_eq!(interaction.message().len(), 2);
            }
            assert_eq!(
                memory.message()[0].values()[..3],
                cols.aligned_low.map(mapped)
            );
            assert_eq!(
                memory.message()[0].values()[3..],
                cols.address.value[3..]
                    .iter()
                    .copied()
                    .map(mapped)
                    .collect::<Vec<_>>()
            );
            let event = events.get(row);
            assert_eq!(
                decode(&values, memory.message()[0].values()),
                event.map_or(0, |e| e.b.wrapping_add(e.c) & !7)
            );
            assert_eq!(
                decode(&values, memory.message()[1].values()),
                event.map_or(0, |e| e.memory_value)
            );
            assert_eq!(register.message()[0].encoding(), InteractionEncoding::Bits);
            assert_eq!(
                decode(&values, register.message()[0].values()),
                event.map_or(0, |e| if e.opcode == LoadByteOpcode::Lb { 1 } else { 2 })
            );
            assert_eq!(register.message()[1].values(), cols.result.map(mapped));
            assert_eq!(
                decode(&values, register.message()[1].values()),
                expected[row]
            );
        }
    }
}

#[test]
fn every_byte_offset_and_signed_result_match_the_native_semantics() {
    let chip = LoadByteCircuit::build(1);
    for opcode in [LoadByteOpcode::Lb, LoadByteOpcode::Lbu] {
        for offset in 0..8 {
            for byte in 0..256u64 {
                let event = event(opcode, 0x1_0000, offset, byte << (8 * offset));
                let trace = chip.generate_trace(&[event]).unwrap();
                assert_eq!(chip.output(&trace.values, 0), event.result());
                assert_eq!(
                    trace.rows[0].sign,
                    opcode == LoadByteOpcode::Lb && byte >= 128
                );
            }
        }
    }
}
