use super::*;
use flock_core::circuit::boolean::{EvaluationError, InteractionDirection};

// Generated by memory/instructions/load/load_byte.rs at SP1 commit
// 4f56564727906846f80b30532dde26eacfc7e44c via LoadByteChip::generate_trace.
const SP1_TRACE_ROWS: [Sp1TraceRow; 3] = [
    Sp1TraceRow {
        is_lb: true,
        address_limbs: [2, 1, 0],
        offset: [false, true, false],
        memory_limbs: [8721, 17459, 26197, 34935],
        selected_limb: 17459,
        selected_low: 51,
        selected_byte: 51,
        msb: false,
    },
    Sp1TraceRow {
        is_lb: true,
        address_limbs: [7, 2, 0],
        offset: [true, true, true],
        memory_limbs: [8208, 16432, 24656, 32880],
        selected_limb: 32880,
        selected_low: 112,
        selected_byte: 128,
        msb: true,
    },
    Sp1TraceRow {
        is_lb: false,
        address_limbs: [5, 3, 0],
        offset: [true, false, true],
        memory_limbs: [12816, 30292, 47768, 65244],
        selected_limb: 47768,
        selected_low: 152,
        selected_byte: 186,
        msb: false,
    },
];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Sp1TraceRow {
    is_lb: bool,
    address_limbs: [u16; 3],
    offset: [bool; 3],
    memory_limbs: [u16; 4],
    selected_limb: u16,
    selected_low: u8,
    selected_byte: u8,
    msb: bool,
}

fn event(opcode: LoadByteOpcode, b: u64, c: u64, memory_value: u64) -> LoadByteEvent {
    LoadByteEvent {
        opcode,
        b,
        c,
        memory_value,
    }
}

fn k_log(circuit: &BooleanCircuit) -> usize {
    circuit
        .walk_plan()
        .unwrap()
        .useful_bits()
        .next_power_of_two()
        .trailing_zeros() as usize
}

fn decode(values: &[bool], bits: &[ValueId]) -> u64 {
    bits.iter().enumerate().fold(0, |word, (bit, value)| {
        word | (u64::from(values[value.index()]) << bit)
    })
}

fn port_value(circuit: &BooleanCircuit, values: &[bool], name: &str) -> u64 {
    decode(values, circuit.port(name).unwrap().values())
}

#[test]
fn lb_and_lbu_match_checked_sp1_trace() {
    let rows = [
        event(LoadByteOpcode::Lb, 0x1_0000, 2, 0x8877_6655_4433_2211),
        event(LoadByteOpcode::Lb, 0x2_0000, 7, 0x8070_6050_4030_2010),
        event(LoadByteOpcode::Lbu, 0x3_0004, 1, 0xfedc_ba98_7654_3210),
    ];
    let chip = LoadByteCircuit::build(4, AssertionMode::Direct);
    let inputs = chip.honest_inputs(&rows);
    let values = chip.circuit().evaluate(&inputs).unwrap();
    assert_eq!(
        rows.map(LoadByteEvent::result),
        [0x33, 0xffff_ffff_ffff_ff80, 0xba]
    );

    for (row, (event, sp1)) in rows.iter().zip(SP1_TRACE_ROWS).enumerate() {
        let address = event.b.wrapping_add(event.c);
        let address_limbs = std::array::from_fn(|limb| (address >> (16 * limb)) as u16);
        let offset = std::array::from_fn(|bit| address >> bit & 1 == 1);
        let memory_limbs = std::array::from_fn(|limb| (event.memory_value >> (16 * limb)) as u16);
        let selected_limb = memory_limbs[((address >> 1) & 3) as usize];

        assert_eq!(sp1.address_limbs, address_limbs);
        assert_eq!(sp1.offset, offset);
        assert_eq!(sp1.memory_limbs, memory_limbs);
        assert_eq!(sp1.selected_limb, selected_limb);
        assert_eq!(sp1.selected_low, selected_limb as u8);
        assert_eq!(
            sp1.selected_byte,
            (selected_limb >> (8 * (address & 1))) as u8
        );
        assert_eq!(sp1.msb, sp1.is_lb && sp1.selected_byte >> 7 == 1);

        let prefix = format!("load-byte.row-{row}");
        assert_eq!(
            port_value(chip.circuit(), &values, &format!("{prefix}.is-lb")),
            u64::from(sp1.is_lb)
        );
        assert_eq!(
            port_value(chip.circuit(), &values, &format!("{prefix}.is-lbu")),
            u64::from(!sp1.is_lb)
        );
        assert_eq!(
            port_value(chip.circuit(), &values, &format!("{prefix}.selected-byte")),
            u64::from(sp1.selected_byte)
        );
        let memory = &chip.circuit().interactions()[2 * row];
        assert!(values[memory.selector().index()]);
        assert_eq!(decode(&values, memory.message()[0].values()), address & !7);
        assert_eq!(
            decode(&values, memory.message()[1].values()),
            event.memory_value
        );
        assert_eq!(chip.output(&values, row), event.result());
        let sp1_result = if sp1.msb {
            u64::MAX << 8 | u64::from(sp1.selected_byte)
        } else {
            u64::from(sp1.selected_byte)
        };
        assert_eq!(chip.output(&values, row), sp1_result);
    }
    assert_eq!(chip.output(&values, 3), 0);

    let k_log = k_log(chip.circuit());
    let r1cs = chip.circuit().to_block_r1cs(k_log, 0, 0).unwrap();
    let walked = chip
        .circuit()
        .walk_plan()
        .unwrap()
        .forward(&inputs, k_log)
        .unwrap();
    assert!(r1cs.satisfies(&walked.z));
    assert_eq!(walked.a_z, r1cs.apply_a(&walked.z));
    assert_eq!(walked.b_z, r1cs.apply_b(&walked.z));
    assert_eq!(walked.c_z, r1cs.apply_c(&walked.z));
}

#[test]
fn all_offsets_and_carry_boundaries_match_the_reference() {
    let chip = LoadByteCircuit::build(1, AssertionMode::Direct);
    let k_log = k_log(chip.circuit());
    let r1cs = chip.circuit().to_block_r1cs(k_log, 0, 0).unwrap();
    let plan = chip.circuit().walk_plan().unwrap();
    let memory = u64::from_le_bytes([0x00, 0x7f, 0x80, 0xff, 0x01, 0x81, 0x42, 0xc3]);
    let mut cases = Vec::new();

    for offset in 0..8 {
        for opcode in [LoadByteOpcode::Lb, LoadByteOpcode::Lbu] {
            cases.push(event(opcode, 0x1_0000, offset, memory));
        }
    }
    cases.extend([
        // Carry across the lower address guard.
        event(LoadByteOpcode::Lbu, 0xffff, 1, memory),
        // Carry through 47 consecutive low bits while remaining in range.
        event(LoadByteOpcode::Lb, 0x7fff_ffff_ffff, 1, memory),
        // Final carry is dropped: u64::MAX + 0x1_0001 = 0x1_0000.
        event(LoadByteOpcode::Lbu, u64::MAX, 0x1_0001, memory),
    ]);

    for event in cases {
        let inputs = chip.honest_inputs(&[event]);
        let values = chip.circuit().evaluate(&inputs).unwrap();
        assert_eq!(chip.output(&values, 0), event.result());

        let sparse = chip.circuit().evaluate_r1cs(&inputs, k_log).unwrap();
        let walked = plan.forward(&inputs, k_log).unwrap();
        assert_eq!(walked.z, sparse);
        assert!(r1cs.satisfies(&walked.z));
        assert_eq!(walked.a_z, r1cs.apply_a(&walked.z));
        assert_eq!(walked.b_z, r1cs.apply_b(&walked.z));
        assert_eq!(walked.c_z, r1cs.apply_c(&walked.z));
    }

    // This carry crosses the exclusive upper address bound.
    let upper_carry = event(LoadByteOpcode::Lbu, (1 << 48) - 1, 1, memory);
    assert!(matches!(
        chip.circuit().evaluate(&chip.honest_inputs(&[upper_carry])),
        Err(EvaluationError::UnsatisfiedRow(_))
    ));
}

#[test]
fn interaction_messages_use_computed_values_and_disable_padding() {
    let row = event(LoadByteOpcode::Lb, 0x1_0003, 2, 0x8877_6655_4433_2211);
    let chip = LoadByteCircuit::build(2, AssertionMode::Direct);
    let values = chip
        .circuit()
        .evaluate(&chip.honest_inputs(&[row]))
        .unwrap();
    assert_eq!(chip.circuit().interactions().len(), 4);

    let memory = &chip.circuit().interactions()[0];
    assert_eq!(memory.channel(), "memory");
    assert_eq!(memory.kind(), "read");
    assert_eq!(memory.direction(), InteractionDirection::Send);
    assert_eq!(memory.scope().row(), 0);
    assert!(values[memory.selector().index()]);
    assert_eq!(memory.effective_multiplicity_bits(&values), [true]);
    assert_eq!(decode(&values, memory.message()[0].values()), 0x1_0000);
    assert_eq!(
        decode(&values, memory.message()[1].values()),
        row.memory_value
    );

    let register = &chip.circuit().interactions()[1];
    assert_eq!(register.channel(), "register");
    assert_eq!(decode(&values, register.message()[0].values()), 1);
    assert_eq!(
        decode(&values, register.message()[1].values()),
        row.result()
    );

    for interaction in &chip.circuit().interactions()[2..] {
        assert_eq!(interaction.scope().row(), 1);
        assert!(!values[interaction.selector().index()]);
        assert_eq!(decode(&values, interaction.multiplicity()), 1);
        assert_eq!(interaction.effective_multiplicity_bits(&values), [false]);
    }
}

#[test]
fn selectors_enforce_exclusivity_and_a_real_row_prefix() {
    let chip = LoadByteCircuit::build(2, AssertionMode::Direct);
    let real = event(LoadByteOpcode::Lbu, 0x1_0000, 0, 0x42);
    let non_prefix = chip.encode_rows(&[None, Some(real)]);
    assert!(matches!(
        chip.circuit().evaluate(&non_prefix),
        Err(EvaluationError::UnsatisfiedRow(_))
    ));

    let mut both_opcodes = chip.encode_rows(&[Some(real), None]);
    both_opcodes[0] = true;
    both_opcodes[1] = true;
    assert!(matches!(
        chip.circuit().evaluate(&both_opcodes),
        Err(EvaluationError::UnsatisfiedRow(_))
    ));
}

#[test]
fn active_addresses_obey_sp1_bounds() {
    let chip = LoadByteCircuit::build(1, AssertionMode::Direct);
    for row in [
        event(LoadByteOpcode::Lbu, 0xffff, 0, 0),
        event(LoadByteOpcode::Lbu, 1 << 48, 0, 0),
    ] {
        assert!(matches!(
            chip.circuit().evaluate(&chip.honest_inputs(&[row])),
            Err(EvaluationError::UnsatisfiedRow(_))
        ));
    }

    for address in [1 << 16, (1 << 48) - 1] {
        let row = event(LoadByteOpcode::Lbu, address, 0, 0);
        assert!(chip.circuit().evaluate(&chip.honest_inputs(&[row])).is_ok());
    }
}

#[test]
fn advice_is_checked_only_on_active_rows() {
    let chip = LoadByteCircuit::build(1, AssertionMode::Direct);
    let row = event(LoadByteOpcode::Lbu, 0x1_0000, 0, 0x42);
    let inputs = chip.honest_inputs(&[row]);
    let k_log = k_log(chip.circuit());
    let r1cs = chip.circuit().to_block_r1cs(k_log, 0, 0).unwrap();
    let witness = chip.circuit().evaluate_r1cs(&inputs, k_log).unwrap();

    let advice = chip
        .circuit()
        .port("load-byte.row-0.selected-byte")
        .unwrap();
    let mut bad_advice = witness.clone();
    bad_advice[advice.values()[0].index()] ^= true;
    assert!(!r1cs.satisfies(&bad_advice));

    let output = chip.circuit().port("load-byte.row-0.result").unwrap();
    let mut bad_output = witness;
    bad_output[output.values()[0].index()] ^= true;
    assert!(!r1cs.satisfies(&bad_output));

    let mut padding = chip.encode_rows(&[None]);
    let advice_start = padding.len() - 8;
    padding[advice_start..].fill(true);
    assert!(chip.circuit().evaluate(&padding).is_ok());
}

#[test]
fn identity_c_needs_its_terminal_binding() {
    let row = event(LoadByteOpcode::Lbu, 0x1_0000, 0, 0x42);
    let direct = LoadByteCircuit::build(1, AssertionMode::Direct);
    let identity = LoadByteCircuit::build(1, AssertionMode::IdentityC);
    let direct_inputs = direct.honest_inputs(&[row]);
    let identity_inputs = identity.honest_inputs(&[row]);

    assert!(!direct.circuit().walk_plan().unwrap().c_is_identity());
    assert!(identity.circuit().walk_plan().unwrap().c_is_identity());
    let honest = identity.circuit().evaluate(&identity_inputs).unwrap();
    assert!(honest[identity.accept().unwrap().index()]);

    let mut bad_direct = direct_inputs;
    *bad_direct.last_mut().unwrap() ^= true;
    assert!(matches!(
        direct.circuit().evaluate(&bad_direct),
        Err(EvaluationError::UnsatisfiedRow(_))
    ));

    let mut bad_identity = identity_inputs;
    *bad_identity.last_mut().unwrap() ^= true;
    let unchecked = identity.circuit().evaluate(&bad_identity).unwrap();
    assert!(!unchecked[identity.accept().unwrap().index()]);
    let k_log = k_log(identity.circuit());
    let r1cs = identity.circuit().to_block_r1cs(k_log, 0, 0).unwrap();
    let witness = identity
        .circuit()
        .evaluate_r1cs(&bad_identity, k_log)
        .unwrap();
    assert!(
        r1cs.satisfies(&witness),
        "local identity-C rows alone accept"
    );

    assert_eq!(
        (
            direct.circuit().value_count(),
            direct.circuit().row_count(),
            direct.circuit().normalized_support_bytes(),
            direct.circuit().walk_plan().unwrap().stats().action_bytes,
        ),
        (551, 577, 10_040, 99_920)
    );
    assert_eq!(
        (
            identity.circuit().value_count(),
            identity.circuit().row_count(),
            identity.circuit().normalized_support_bytes(),
            identity.circuit().walk_plan().unwrap().stats().action_bytes,
        ),
        (603, 603, 13_156, 106_144)
    );
    assert!(direct.circuit().row_count() < identity.circuit().row_count());
    assert!(direct.circuit().value_count() < identity.circuit().value_count());
}

#[test]
fn direct_and_bound_identity_c_reject_the_same_inputs() {
    let direct = LoadByteCircuit::build(2, AssertionMode::Direct);
    let identity = LoadByteCircuit::build(2, AssertionMode::IdentityC);
    let row = event(LoadByteOpcode::Lb, 0x1_0000, 7, 0x8070_6050_4030_2010);
    let valid = direct.honest_inputs(&[row]);
    let non_prefix = direct.encode_rows(&[None, Some(row)]);
    let bad_address = direct.honest_inputs(&[event(LoadByteOpcode::Lb, 0xffff, 0, 0)]);
    let mut bad_advice = valid.clone();
    bad_advice[201] ^= true;
    let mut both_selectors = valid.clone();
    both_selectors[0] = true;
    both_selectors[1] = true;

    for inputs in [valid, non_prefix, bad_address, bad_advice, both_selectors] {
        let direct_accepts = direct.circuit().evaluate(&inputs).is_ok();
        let identity_values = identity.circuit().evaluate(&inputs).unwrap();
        let identity_accepts = identity_values[identity.accept().unwrap().index()];
        assert_eq!(direct_accepts, identity_accepts);
    }
}
